### ISSUE TITLE
Trouble with long image path

### ISSUE THREAD

**Issue by Cloudzaaa** [botflux/gulp-picture#1]
I have had a trouble with long image path. 
For example If our root path is src/img, after plugin executed it becomes incorrect for a second srcset (reversed)
you can see it on the screenshot http://dl4.joxi.net/drive/2019/04/27/0032/1048/2118680/80/6a15310c6e.png

**Comment by botflux** [comment]
Thanks for the report. Could you share your gulp configuration or a repo link so I can directly test ?

**Comment by botflux** [comment]
https://www.npmjs.com/package/gulp-picture
I've released a version that should correct the problem. Let me know if this issue persist or not.

**Comment by Cloudzaaa** [comment]
> https://www.npmjs.com/package/gulp-picture
> I've released a version that should correct the problem. Let me know if this issue persist or not.

Thank you, it's solved
